### ISSUE TITLE
Proposal for the bounty

### ISSUE THREAD

**Issue by akshatbhargava123** [ProlificLabs/sqlclone#1]
I saw that the bounty has been recently assigned to someone else but would have loved to work on it, here's the proposal I wrote but missed to publish on time:

This seems like an interesting project (given that it’s also going to be open source), I can ship this within 1 week (including testing) from whenever it is assigned to me. Even though you’ve shared most of the pieces of execution (like functional design of the library), I’ll still share my own thoughts here:

- Starting with choosing a Go client, do you have preference about what sql go client we should use to accomplish this? If not, I’ll mostly be using database/sql which is more low-level.
- Once a client is finalised, we’ll need the following utility functions (either from db client lib or our own):
  - Function to identify schema [params: tableName]
  - Function to fetch structure of foreign key references (tables and their schema) [params: srcTableName]
  - Function to fetch all the foreign key records (params: source row [rowId, tableName], foreignTableName)

Once that is done, we can probably also use go-routines to parallelise the function calls and do it concurrently for each foreign reference table or each row of the recursive chain to improve performance (even though it isn't a big deal for now).

You’ve mentioned a basic test in the requirement but it would still be great if you could provide a test DB dump which you think could make the testing more robust. I’ll also ship automated tests with some of the core cases covered.

Here's my social profiles:
- https://www.linkedin.com/in/akshatbhargava123/
- https://twitter.com/akshatB123

Bounty ref (for context): https://replit.com/bounties/@MarkErdmann/go-package-that-clon

**Comment by markerdmann** [comment]
@akshatbhargava123 Thank you for your proposal! We accepted a proposal this morning, but I'll make sure to reach out when we have new bounties coming up.
